"""mirror clerk role and permissions on users

Revision ID: 6ab70b3540ef
Revises: 5a64145c21d4
Create Date: 2026-08-20 23:36:36.555898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ab70b3540ef'
down_revision: Union[str, Sequence[str], None] = '5a64145c21d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), server_default='member', nullable=False))
    op.add_column('users', sa.Column('permissions', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permissions')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
