"""create blogs

Revision ID: 9fd29265d252
Revises: 5695b55fd8f7
Create Date: 2026-08-27 22:17:57.089174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd29265d252'
down_revision: Union[str, Sequence[str], None] = '5695b55fd8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('excerpt', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('cover_image_key', sa.String(length=500), nullable=True),
    sa.Column('published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_blogs_slug')
    )
    op.create_index(op.f('ix_blogs_creator_id'), 'blogs', ['creator_id'], unique=False)
    op.create_index('ix_blogs_published_at', 'blogs', ['published_at'], unique=False, postgresql_where=sa.text('published'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blogs_published_at', table_name='blogs', postgresql_where=sa.text('published'))
    op.drop_index(op.f('ix_blogs_creator_id'), table_name='blogs')
    op.drop_table('blogs')
    # ### end Alembic commands ###
